name: build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true

    runs-on: actuated
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Local build
        id: local_build
        uses: docker/build-push-action@v3
        with:
          outputs: "type=docker,push=false"
          platforms: linux/amd64
          build-args: |
            Version=dev
            GitCommit=${{ github.sha }}
          tags: |
            ghcr.io/inlets/inlets-operator:${{ github.sha }}
